openapi: "3.0.1"
info:
  title: Tshirt Store
  descripition: An ecommerce site for tshirts
  version: 1.0.0
  contact:
    email: luckybigwings@gmail.com

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    descripition: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer