openapi: "3.0.1"
info:
  title: Tshirt Store
  descripition: An ecommerce site for tshirts
  version: 1.0.0
  contact:
    email: luckybigwings@gmail.com

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    descripition: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: return a greet message
      responses:
        200:
          descripition: All good and success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          descripition: Bad request
        500: 
          descripition: Internal server error

  /signup:
    post:
      tags:
        - User
      summary: signup a new user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - photo
              properties:
                name:
                  type: string
                  required: true
                email:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
                photo:
                  in: formData
                  descripition: Uploaded file data
                  type: file
                  format: binary
      responses:
        200:
          descripition: All good and success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secure_url:
                            type: string
                      _id:
                        type: string
                      createdAt:
                        type: string
        400:
          descripition: Bad request
        500:
          descripition: Internal server error